# syntax=docker/dockerfile:1
FROM python:3.11.4

ENV PYTHONUNBUFFERED=1
ENV PYTHON_BIN=python

WORKDIR /code

# install system dependencies
RUN apt update && apt install git -y

# cleanup apt cache
RUN rm -rf /var/lib/apt/lists/*

COPY taskiq_matrix /code/taskiq_matrix
COPY pyproject.toml /code/
COPY README.md /code/
COPY tests /code/tests

COPY .coveragerc conftest.py pytest.ini /code/

# install package
RUN pip3 install git+https://github.com/fractalnetworksco/fractal-matrix-client.git@main
RUN pip3 install -e /code[dev]

COPY test-config /test-config

ENTRYPOINT [ "/test-config/entrypoint.sh" ]
