FROM matrixdotorg/synapse:v1.95.1

ARG SYNAPSE_SERVER_NAME=localhost
ARG SYNAPSE_REPORT_STATS=no

RUN apt update; apt install sqlite3 -y
RUN rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data

RUN bash -c 'python /start.py generate'

COPY config_to_add.yaml /config_to_add.yaml

# append config to homeserver.yaml only if it's not already there
RUN cat /config_to_add.yaml >> /data/homeserver.yaml

ENTRYPOINT bash -c ' \
    python /start.py &> /dev/null'
