name: CI

on:
  push:
    branches:
      - '**' # This will run the workflow on every push to any branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: make test-ci
  
  pypi-publish:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Poetry & Build
        run: pip install poetry; poetry build

      - name: Bump version and commit
        run: |
          poetry version patch
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@users.noreply.github.com'
          git commit -am "Bump version"
          git push

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
